question_data = {"response_code": 0, "results": [{"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "Israel is 7 hours ahead of New York.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "Vietnam is the only country in the world that starts with V. ",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "Gothenburg is the capital of Sweden.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "&quot;Mongolia&quot; was a part of the now non-existent U.S.S.R.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "Antarctica is the largest desert in the world.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "You could walk from Norway to North Korea while only passing through Russia.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "Liechtenstein does not have an airport.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "The title of the 1969 film &quot;Krakatoa, East_of Java&quot; is incorrect, as Krakatoa is in fact west of Java.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "Is Tartu the capital of Estonia?",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]}]}

# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are "
#              "free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]
